### ISSUE TITLE
NotImplementedError with file observer

### ISSUE THREAD

**Issue by devxpy** [codelv/enaml-web#10]
https://github.com/codelv/enaml-web/blob/ff29147f051f6ff47d463718968bfc2ec691514c/web/impl/lxml_app.py#L83

```
from web.impl.lxml_app import LxmlApplication
import signal

def main():
    app = LxmlApplication()
    app.init_reloader()
    signal.pause()
```

results in 

```
Detected changes in ./index.enaml, scheduling reload...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/dev/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/dev/.local/share/virtualenvs/quiz_backend-RJ5HRaNa/lib/python3.6/site-packages/watchdog/observers/api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "/home/dev/.local/share/virtualenvs/quiz_backend-RJ5HRaNa/lib/python3.6/site-packages/watchdog/observers/api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "/home/dev/.local/share/virtualenvs/quiz_backend-RJ5HRaNa/lib/python3.6/site-packages/watchdog/events.py", line 322, in dispatch
    self.on_any_event(event)
  File "/home/dev/.local/share/virtualenvs/quiz_backend-RJ5HRaNa/lib/python3.6/site-packages/web/impl/lxml_app.py", line 83, in on_any_event
    app.deferred_call(self.queue_reload)
  File "/home/dev/.local/share/virtualenvs/quiz_backend-RJ5HRaNa/lib/python3.6/site-packages/enaml/application.py", line 278, in deferred_call
    raise NotImplementedError
NotImplementedError

```

**Comment by frmdstryr** [comment]
The LxmlApplication does not integrate with a server so reloading doesn't make sense. 

Djangos dev server should handle this for you.

**Comment by frmdstryr** [comment]
You want to have it recreate the static site when a file changes?

**Comment by devxpy** [comment]
Yeah figured that would do it.

Btw, is there any way to integrate django template expressions into enaml?

**Comment by devxpy** [comment]
https://github.com/codelv/enaml-web/issues/11
