### ISSUE TITLE
Error on pip install

### ISSUE THREAD

**Issue by vahndi** [codelv/enaml-web#2]
```
pip install git+https://github.com/codelv/enaml-web.git
```

```
Collecting git+https://github.com/codelv/enaml-web.git
  Cloning https://github.com/codelv/enaml-web.git to /private/var/folders/mn/wzflzlvn1ngg1vtyzd0s4sgc0000gn/T/pip-f734ms7a-build
Collecting distribute (from enaml-web==0.1.0)
  Using cached distribute-0.7.3.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mn/wzflzlvn1ngg1vtyzd0s4sgc0000gn/T/pip-build-4lkpjyuv/distribute/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/private/var/folders/mn/wzflzlvn1ngg1vtyzd0s4sgc0000gn/T/pip-build-4lkpjyuv/distribute/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "/private/var/folders/mn/wzflzlvn1ngg1vtyzd0s4sgc0000gn/T/pip-build-4lkpjyuv/distribute/setuptools/dist.py", line 7, in <module>
        from setuptools.command.install import install
      File "/private/var/folders/mn/wzflzlvn1ngg1vtyzd0s4sgc0000gn/T/pip-build-4lkpjyuv/distribute/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/private/var/folders/mn/wzflzlvn1ngg1vtyzd0s4sgc0000gn/T/pip-build-4lkpjyuv/distribute/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/private/var/folders/mn/wzflzlvn1ngg1vtyzd0s4sgc0000gn/T/pip-build-4lkpjyuv/distribute/pkg_resources.py", line 1518, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/mn/wzflzlvn1ngg1vtyzd0s4sgc0000gn/T/pip-build-4lkpjyuv/distribute/

```

**Comment by frmdstryr** [comment]
Thanks for reporting this! Can you please provide some more details on your environment? (Python version, os, etc...)

**Comment by vahndi** [comment]
Sure! Python 3.6 with OSX Yosemite.
Btw I got it to install by installing ```enaml``` separately, cloning and then running ```setup.py```
```
conda create -n enaml_web_env python=3.6
conda install -n enaml_web_env enaml -c ecpy
source activate enaml_web_env
git clone https://github.com/codelv/enaml-web.git
cd enaml-web/
python setup.py install
```
